<?php
require('htmlToPdf.php');
include('../../resources/functions.php');
$report_arr = array();
$store_id = $_POST['storeid'];
$productid = $_POST['productid'];
$Count = 0;
$transaction_type = $_POST['transaction_type'];
$coupon_type = $_POST['coupon_type'];
$array = explode(' - ', $_POST['dateval']);
foreach($array as $value) {

	if($Count == 0 ) {
		$Date1 = $value;
	}elseif ($Count > 0) {
		$Date2 = $value;
	}

$Count += 1;

}

$Date1 = date_create($Date1);
$Date1 = date_format($Date1,"Y-m-d");

$Date2 = date_create($Date2);
$Date2 = date_format($Date2,"Y-m-d");

$filter_store = '';
$filter_product = '';
$filter_transaction_type = '';
$filter_coupon_type = '';

if($store_id != 'All'){
    $filter_store = " AND a.store_id = '".$store_id."' ";
}

if($productid != 'All'){
    $filter_product = " AND a.product_name = '".$productid."' ";
}

if($transaction_type != 'All'){
    if($transaction_type == 'All(Cash)'){
        $filter_transaction_type = " AND a.transaction_type = 'Walk-In' ";
    }else if($transaction_type == 'All(Others)'){
        $filter_transaction_type = " AND a.transaction_type != 'Walk-In' ";
    }else{
        $filter_transaction_type = " AND a.transaction_type = '".$transaction_type."' ";
    }
    
}

if($coupon_type != 'All'){
    $filter_coupon_type = " AND c.discount_type = '".$coupon_type."' ";
}

$sql = "SELECT a.*,DATE(a.created_at) t_date,b.store_name,c.discount_type FROM posrev.admin_daily_transaction_details a 
inner join posrev.admin_outlets b on b.store_id = a.store_id  
inner join posrev.admin_daily_transaction c on c.transaction_number = a.transaction_number
WHERE DATE_FORMAT(a.zreading, '%Y-%m-%d') >= '".$Date1."' AND DATE_FORMAT(a.zreading, '%Y-%m-%d') <= '".$Date2."' 
".$filter_store." ".$filter_product." ".$filter_transaction_type." ".$filter_coupon_type." ";

$result = query($sql);
confirm($result);
$total_items = 0;

while($row = mysqli_fetch_array($result)){
    
    $total_items +=  $row['quantity'];

    $report_arr[] = array("id" => $row['details_id'],"store_name" => $row['store_name'], "name" => $row['product_sku'], 
                        "transaction_number" => $row['transaction_number'], 'quantity' => $row['quantity'] 
                        ,'price'=>$row['price'],'total'=>$row['total'],'Transaction_type'=>$row['transaction_type'],
                        'discount_type'=>$row['discount_type'],
                        'Transaction_date'=>$row['t_date'],'Read_Date'=>$row['zreading']);

    
}
// echo json_encode($report_arr);
$t_row = array();
for($i = 0; $i < count($report_arr); $i++){
    $t_row[] = array('strore'=>$report_arr[$i]['store_name'],'tn'=>$report_arr[$i]['transaction_number'],
                'prod'=>$report_arr[$i]['name'],'qty'=>$report_arr[$i]['quantity'],'price'=>$report_arr[$i]['price'],
                'total'=>$report_arr[$i]['total'],'Transaction_type'=>$report_arr[$i]['Transaction_type'],
                'discount_type'=>$report_arr[$i]['discount_type'],
                'Transaction_date'=>$report_arr[$i]['Transaction_date'],'date'=>$report_arr[$i]['Read_Date']);
}


$sql1 = "SELECT c.* FROM posrev.admin_daily_transaction_details a 
inner join posrev.admin_outlets b on b.store_id = a.store_id  
inner join posrev.admin_daily_transaction c on c.transaction_number = a.transaction_number
WHERE DATE_FORMAT(a.zreading, '%Y-%m-%d') >= '".$Date1."' AND DATE_FORMAT(a.zreading, '%Y-%m-%d') <= '".$Date2."' 
".$filter_store." ".$filter_product." ".$filter_transaction_type." ".$filter_coupon_type." group by c.transaction_number";

$result1 = query($sql1);
confirm($result1);

$total_sales = 0;
$vatable_sales = 0;
$lessvatable_sales = 0;
$discount = 0;
while($row1 = mysqli_fetch_array($result1)){
    $total_sales +=  $row1['amountdue'];
    $vatable_sales +=  $row1['vatablesales'];
    $lessvatable_sales +=  $row1['lessvat'];
    $discount +=  $row1['totaldiscount'];
}

if(isset($_SERVER['HTTPS'])){
    $protocols = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
}
else{
    $protocol = 'http';
}
 $protocol .= "://" . $_SERVER['HTTP_HOST'];

$heading='
      <span>Date From - To: '.$_POST['dateval'].'</span><br>
      <span>Product Name: '.$productid.'</span><br>
      <span>Transaction Type: '.$transaction_type.'</span><br>
      <span>Discount Type: '.$coupon_type.'</span><br>';
    
    $footer='
    <span>Total Items : '.$total_items.'</span><br>
    <span>Net Sales: '.number_format($total_sales,2).'</span><br>
    <span>Vatable Sales: '.number_format($vatable_sales,2).'</span><br>
    <span>Less Vat Sales: '.number_format($lessvatable_sales,2).'</span><br>
    <span>Discounts: '.number_format($discount,2).'</span><br>
    <span>Date generated: '.date('m-d-Y').'</span><br><br><br>
    <i>*This report is generated by '.$protocol.'</i>';
    
$header = array('Store ID', 'Transaction #', 'Product SKU', 'Quantity','Price','Total','Transaction Type','Discount Type','Transaction Date','Read Date');
$pdf=new PDF_HTML();
$pdf->SetFont('Arial','',10.5);
$pdf->AddPage('L','Legal',0);
$pdf->WriteHTML($heading);
$pdf->BasicTable($header,$t_row);
$pdf->WriteHTML($footer);
$filename = $pdf->Output('F');
echo $filename;


?>